# permissions to do viewer benchmarksqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benchmarksql-viewer-role
rules:
- apiGroups:
  - pingcap.pingcap.com
  resources:
  - benchmarksqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pingcap.pingcap.com
  resources:
  - benchmarksqls/status
  verbs:
  - get
